### ISSUE TITLE
Update for 0.6 compatibility

### ISSUE THREAD

**Issue by penntaylor** [penntaylor/DBaseReader.jl#2]
* Language keywords for composite datatypes are changing in 0.6
* Check use of ASCIIString...don't recall offhand whether that has changed

**Comment by loicspace** [comment]
Hi!

Any updates on this? Do you plan on maintaining the package?
I have fixed up the language issues to make it work with 0.6 -- not prettily -- but I imagine it is only a mater of time before something else breaks...
It is a very useful tool and except if thee is something out there, I rely on it in my own tool to read database files that are associated with continent shape files to do coverage analysis on Earth from space.
So thanks for the package!

Cheers,

Loic

**Comment by penntaylor** [comment]
I will work on this tonight. Glad to hear that someone is using the package!

**Comment by penntaylor** [comment]
Master branch should now work correctly with julia 0.6.
Works fine with 0.7, although with some deprecation warnings.

**Comment by loicspace** [comment]
Great, thanks !
